name: Integration Testing for Kestrel and STIX-Shifter Using GitHub Actions
on: 
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  integrated-testing:
    runs-on: ubuntu-20.04
    steps:
      - name: Worflow Information
        run: |
          echo "Triggered by ${{ github.actor }} through a ${{ github.event_name }} event."
          echo "Running on a ${{ runner.os }} server hosted by GitHub"
          echo "Running in ${{ github.repository }} repository, ${{ github.ref }} branch."
          echo "HOME = ${HOME}"
      - name: Code Checkout
        uses: actions/checkout@v3
      - name: Kestrel Code Checkout
        uses: actions/checkout@v3
        with:
          repository: opencybersecurityalliance/kestrel-lang
          ref: develop_stixshifter_v5
          path: './kestrel-lang'
      - name: STIX-Shifter Code Checkout
        uses: actions/checkout@v3
        with:
          repository: opencybersecurityalliance/stix-shifter
          path: './stix-shifter'
      - name: Create Virtual Environment
        run: |
          ./create-venv.sh
          . huntingtest/bin/activate
          echo "venv_activate=$VIRTUAL_ENV/bin/activate" >> $GITHUB_ENV
      - name: Install kestrel and STIX-Shifter from Source Code
        run: |
          source ${{ env.venv_activate }}
          cd ${{ github.workspace }} 
          ./install-stix-shifter-kestrel.sh
      - name: Elasticsearch instance setup
        run: |
          source ${{ env.venv_activate }}
          cd ${{ github.workspace }} 
          ./install-elastic.sh
      - name: Import test data in elastic instance
        run: ./import-data.sh
      - name: Check deployment of the test environment
        run: |
          source ${{ env.venv_activate }}
          cd ${{ github.workspace }} 
          ./run_kestrel.sh
      - name: Run Integration Tests
        run: |
          source ${{ env.venv_activate }}
          cd ${{ github.workspace }} 
          ./run-bdd-tests.sh
      - name: Cleanup
        run: |
          docker stop es01test
          docker rm es01test
          docker network rm elastic
          rm -rf data

      - name: Job Status
        run: echo "Job status is ${{ job.status }}."